devschool_admin:
    resource: "@DevschoolAdminBundle/Controller/"
    type:     annotation
    prefix:   /

devschool_biblio_films:
    resource: "@DevschoolBiblioFilmsBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
